server:
    port: 8087
spring:
    application: activity-service
    datasource:
      url: jdbc:mysql://localhost:3306/activity?useSSL=false&serverTimezone=UTC
      driverClassName: com.mysql.cj.jdbc.Driver
      username: root
      password: root
    type: com.alibaba.druid.pool.DruidDataSource
    activiti:
        check-process-definitions: false  #自动检查、部署流程定义文件
        database-schema-update: true
    output:
      ansi:
        enabled: always
logging:
  level:
     root: INFO
  file: spirng111.log
